import {images} from "../../constants/index"

const dummyData = [
  [
    {
      id: 1,
      name: "Science",
      description: "Computer Programming 101",
      level: 937,
      author: "Female",
      banner: images.teacherTeaching,
      favorite: true,
      index: 1,
    },
    {
      id: 2,
      name: "History",
      description: "Computer Programming 101",
      level: 651,
      author: "Female",
      banner: images.pandaGrad,
      favorite: true,
      index: 2,
    },
    {
      id: 3,
      name: "History",
      description: "Computer Programming 101",
      level: 4,
      author: "Male",
      banner: images.onlineLearning,
      favorite: false,
      index: 3,
    },
    {
      id: 4,
      name: "History",
      description: "Literature and Film Studies",
      level: 521,
      author: "Male",
      banner: "http://dummyimage.com/176x100.png/cc0000/ffffff",
      favorite: true,
      index: 4,
    },
    {
      id: 5,
      name: "Mathematics",
      description: "Computer Programming 101",
      level: 766,
      author: "Female",
      banner: "http://dummyimage.com/101x100.png/cc0000/ffffff",
      favorite: false,
      index: 5,
    },
    {
      id: 6,
      name: "History",
      description: "Introduction to Biology",
      level: 371,
      author: "Polygender",
      banner: "http://dummyimage.com/236x100.png/cc0000/ffffff",
      favorite: true,
      index: 6,
    },
    {
      id: 7,
      name: "Mathematics",
      description: "Computer Programming 101",
      level: 526,
      author: "Female",
      banner: "http://dummyimage.com/187x100.png/ff4444/ffffff",
      favorite: false,
      index: 7,
    },
    {
      id: 8,
      name: "English",
      description: "History of Art",
      level: 759,
      author: "Female",
      banner: "http://dummyimage.com/218x100.png/cc0000/ffffff",
      favorite: false,
      index: 8,
    },
    {
      id: 9,
      name: "History",
      description: "Introduction to Biology",
      level: 795,
      author: "Male",
      banner: "http://dummyimage.com/108x100.png/cc0000/ffffff",
      favorite: false,
      index: 9,
    },
    {
      id: 10,
      name: "Mathematics",
      description: "Literature and Film Studies",
      level: 488,
      author: "Female",
      banner: "http://dummyimage.com/250x100.png/cc0000/ffffff",
      favorite: false,
      index: 10,
    },
    {
      id: 11,
      name: "Mathematics",
      description: "Introduction to Biology",
      level: 361,
      author: "Female",
      banner: "http://dummyimage.com/138x100.png/dddddd/000000",
      favorite: true,
      index: 11,
    },
    {
      id: 12,
      name: "Mathematics",
      description: "Literature and Film Studies",
      level: 505,
      author: "Female",
      banner: "http://dummyimage.com/239x100.png/cc0000/ffffff",
      favorite: true,
      index: 12,
    },
    {
      id: 13,
      name: "Science",
      description: "Psychology of Human Behavior",
      level: 144,
      author: "Male",
      banner: "http://dummyimage.com/141x100.png/cc0000/ffffff",
      favorite: false,
      index: 13,
    },
    {
      id: 14,
      name: "Science",
      description: "Computer Programming 101",
      level: 261,
      author: "Male",
      banner: "http://dummyimage.com/163x100.png/cc0000/ffffff",
      favorite: false,
      index: 14,
    },
    {
      id: 15,
      name: "Art",
      description: "History of Art",
      level: 857,
      author: "Female",
      banner: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
      favorite: true,
      index: 15,
    },
  ],
];

export default dummyData;